import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Menu from "@/components/generic/Menu";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
      <Menu/>
      {children}
      </body>
    </html>
  );
}
